name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: esteve/ros-deb-builder-action@continue-packages
        with:
          ROS_DISTRO: debian
          DEB_DISTRO: sid
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: '$verbose = 1;'
          ROSDEP_SOURCE: yaml file:///home/runner/work/moveit_studio_upstream_buildfarm/moveit_studio_upstream_buildfarm/rosdep.yaml ${{ matrix.ros_distro }}
