name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@rosotest
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: rolling
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: '$verbose = 1;'
