name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@v1.0
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: https://raw.githubusercontent.com/ros-planning/moveit2_tutorials/humble/moveit2_tutorials.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: '$verbose = 1;'
