name: sbuild

on:
  workflow_dispatch:
  push:

jobs:
  sbuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [debian]
    env:
      deb_distro: bookworm
    steps:
      - name: Create Debian packages
        uses: jspricke/ros-deb-builder-action@devel
        with:
          DEB_DISTRO: ${{ env.deb_distro }}
          ROS_DISTRO: ${{ matrix.ros_distro }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: 1
          REPOS_FILE: upstream.repos
