name: sbuild

on:
  workflow_dispatch:
  push:

jobs:
  sbuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [noetic]
    env:
      deb_distro: focal
    steps:
      - name: Create Debian packages
        uses: jspricke/ros-deb-builder-action@main
        env:
          DEB_DISTRO: ${{ env.deb_distro }}
          ROS_DISTRO: ${{ matrix.ros_distro }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
